<footer class="container">
    <div class="row res-row">
        <div class="col col-lg-4">
            <img src="../images/logo_small.png" width="143" height="140" alt="TechX small logo" />
        </div>

        <div class="col col-lg-4">
            <h2>Quick Links</h2> <!-- changed from h3 to h2 -->
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="jobs.php">Jobs</a></li>
                <li><a href="apply.php">Apply</a></li>
                <li><a href="about.php">About</a></li>
            </ul>
        </div>
        <div class="social-icon">
            <a href="https://www.facebook.com/" target="_blank">
                <i class="icon_design fab fa-facebook-f" aria-hidden="true"></i>
                <span class="sr-only">Facebook</span>
            </a>

            <a href="https://x.com/" target="_blank">
                <i class="icon_design fab fa-twitter" aria-hidden="true"></i>
                <span class="sr-only">X (Twitter)</span>
            </a>

            <a href="https://web.whatsapp.com/" target="_blank">
                <i class="icon_design fab fa-whatsapp" aria-hidden="true"></i>
                <span class="sr-only">WhatsApp</span>
            </a>

            <a href="https://www.instagram.com/" target="_blank">
                <i class="icon_design fab fa-instagram" aria-hidden="true"></i>
                <span class="sr-only">Instagram</span>
            </a>
        </div>

    </div>

    <hr>

    <p class="copyright">© 2025 TechX Group – All Rights Reserved</p>

    <!-- Fixed Jira Project link -->
    <p class="copyright">
        <a href="https://12housew.atlassian.net/jira/software/projects/GROUP5/boards/34?atlOrigin=eyJpIjoiNGE4NmE2MjkyZGU0NDUyYjgxMDZmMjA3Njk2NzVlNGYiLCJwIjoiaiJ9" target="_blank">
            Jira Project
        </a>
    </p>
    <!-- Added GitHub Link-->
    <p class="copyright">
        <a href="https://github.com/YatiMoe/TechX_part2.git" target="_new">
            GitHub
        </a>
</footer>