	<head>
    	<meta charset="UTF-8">
   		 <meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
  		  <title>TechX</title>

    	<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
		<link rel="icon" type="image/svg+xml" href="../../images/favicon.svg">
		<link href="../styles/styles.css" rel="stylesheet" type="text/css">
		<script src="https://kit.fontawesome.com/88e37bff79.js" crossorigin="anonymous"></script>
		<link rel="icon" type="image/png" href="../images/favicon.png">
		<link rel="icon" type="image/x-icon" href="../images/favicon.ico">
		<link rel="shortcut icon" href="../images/favicon.ico">
		<link rel="icon" href="../images/favicon.svg" type="image/svg+xml">

	</head>