<div class="container banner">
<header>
    <nav class="res-row nav-header">
        <div class="col-lg-3 nav-logo">
        <img src="../images/logo.png" height="90px" alt="Company_logo"/> </div>
        <div class="col-lg-9 nav-list">

                <a href="index.php">Home</a>
                <a class="active" href="jobs.php">Jobs</a>
                <a href="apply.php">Apply</a>
                <a href="about.php">About</a>
      </div>
    </nav>
</header>